import { ElementData, PlasticType } from './types.ts';

export const PLASTICS: Record<string, PlasticType> = {
  PET: {
    id: 'PET',
    code: 1,
    name: 'Polyethylene Terephthalate',
    name_ar: 'بولي إيثيلين تيريفثاليت',
    commonName: 'Polyester',
    structure: 'M10 50',
    formula: '(C_{10}H_{8}O_{4})_n',
    polymerization: 'Condensation Polymerization',
    properties: ['Clear', 'Tough', 'Barrier to gas', 'Lightweight'],
    safety: 'Generally safe for single use. Avoid reheating.',
    safety_ar: 'آمن بشكل عام للاستخدام الواحد. تجنب إعادة التسخين.',
    sustainability: 'Highly Recyclable - Code #1',
    description_ar: 'زجاجات المياه والمشروبات الغازية.',
    recyclabilityScore: 85,
    degradationYears: 450,
    polymerCategory: 'thermoplastic',
    chemicalBonds: 'C-C, C-O, C=O (ester links)',
    commonUses: ['Water bottles', 'Soda bottles', 'Food packaging', 'Polyester fabric'],
    commonUses_ar: ['زجاجات المياه', 'زجاجات المشروبات الغازية', 'تغليف الأطعمة', 'نسيج البوليستر']
  },
  HDPE: {
    id: 'HDPE',
    code: 2,
    name: 'High-Density Polyethylene',
    name_ar: 'بولي إيثيلين عالي الكثافة',
    commonName: 'Polythene',
    structure: '',
    formula: '(C_2H_4)_n',
    polymerization: 'Addition Polymerization',
    properties: ['Stiff', 'Strong', 'Resistant to chemicals', 'Opaque'],
    safety: 'Very safe. Considered one of the safest plastics.',
    safety_ar: 'آمن جداً. يعتبر من أكثر البلاستيك أماناً.',
    sustainability: 'Easily recycled - Code #2',
    description_ar: 'عبوات المنظفات والشامبو.',
    recyclabilityScore: 90,
    degradationYears: 500,
    polymerCategory: 'thermoplastic',
    chemicalBonds: 'C-C, C-H (linear chains)',
    commonUses: ['Milk jugs', 'Detergent bottles', 'Pipes', 'Cutting boards'],
    commonUses_ar: ['علب الحليب', 'زجاجات المنظفات', 'الأنابيب', 'ألواح التقطيع']
  },
  PVC: {
    id: 'PVC',
    code: 3,
    name: 'Polyvinyl Chloride',
    name_ar: 'بولي فينيل كلوريد',
    commonName: 'Vinyl',
    structure: '',
    formula: '(C_2H_3Cl)_n',
    polymerization: 'Addition Polymerization',
    properties: ['Rigid', 'Durable', 'Weather-resistant'],
    safety: 'Contains chlorine. Avoid for food contact.',
    safety_ar: 'يحتوي على الكلور. تجنب استخدامه مع الطعام.',
    sustainability: 'Rarely recycled - Code #3',
    description_ar: 'أنابيب السباكة والنوافذ.',
    recyclabilityScore: 25,
    degradationYears: 600,
    polymerCategory: 'thermoplastic',
    chemicalBonds: 'C-C, C-H, C-Cl',
    commonUses: ['Pipes', 'Window frames', 'Wire insulation', 'Medical tubing'],
    commonUses_ar: ['الأنابيب', 'إطارات النوافذ', 'عزل الأسلاك', 'أنابيب طبية']
  },
  LDPE: {
    id: 'LDPE',
    code: 4,
    name: 'Low-Density Polyethylene',
    name_ar: 'بولي إيثيلين منخفض الكثافة',
    commonName: 'Polythene',
    structure: '',
    formula: '(C_2H_4)_n',
    polymerization: 'Addition Polymerization',
    properties: ['Flexible', 'Soft', 'Transparent'],
    safety: 'Generally safe for food contact.',
    safety_ar: 'آمن بشكل عام للتلامس مع الطعام.',
    sustainability: 'Recyclable but not widely accepted - Code #4',
    description_ar: 'أكياس التسوق والأغلفة.',
    recyclabilityScore: 60,
    degradationYears: 450,
    polymerCategory: 'thermoplastic',
    chemicalBonds: 'C-C, C-H (branched chains)',
    commonUses: ['Plastic bags', 'Squeezable bottles', 'Cling film', 'Coating'],
    commonUses_ar: ['الأكياس البلاستيكية', 'زجاجات قابلة للضغط', 'غلاف بلاستيكي', 'طلاء']
  },
  PP: {
    id: 'PP',
    code: 5,
    name: 'Polypropylene',
    name_ar: 'بولي بروبيلين',
    commonName: 'Polypropylene',
    structure: '',
    formula: '(C_3H_6)_n',
    polymerization: 'Addition Polymerization',
    properties: ['Heat-resistant', 'Tough', 'Fatigue-resistant'],
    safety: 'Very safe. Heat-resistant and microwave-safe.',
    safety_ar: 'آمن جداً. مقاوم للحرارة ومناسب للميكرويف.',
    sustainability: 'Recyclable - Code #5',
    description_ar: 'حاويات الطعام وأغطية الزجاجات.',
    recyclabilityScore: 75,
    degradationYears: 450,
    polymerCategory: 'thermoplastic',
    chemicalBonds: 'C-C, C-H (methyl branches)',
    commonUses: ['Food containers', 'Bottle caps', 'Straws', 'Automotive parts'],
    commonUses_ar: ['حاويات الطعام', 'أغطية الزجاجات', 'الشفاطات', 'قطع السيارات']
  },
  PS: {
    id: 'PS',
    code: 6,
    name: 'Polystyrene',
    name_ar: 'بولي ستايرين',
    commonName: 'Styrofoam',
    structure: '',
    formula: '(C_8H_8)_n',
    polymerization: 'Addition Polymerization',
    properties: ['Lightweight', 'Insulating', 'Brittle'],
    safety: 'May leach styrene when heated. Avoid hot foods.',
    safety_ar: 'قد يتسرب الستايرين عند التسخين. تجنب الأطعمة الساخنة.',
    sustainability: 'Difficult to recycle - Code #6',
    description_ar: 'أكواب القهوة والأطباق البلاستيكية.',
    recyclabilityScore: 15,
    degradationYears: 500,
    polymerCategory: 'thermoplastic',
    chemicalBonds: 'C-C, C-H (aromatic rings)',
    commonUses: ['Disposable cups', 'Foam packaging', 'CD cases', 'Insulation'],
    commonUses_ar: ['أكواب يمكن التخلص منها', 'تعبئة الفوم', 'علب الأقراص', 'العزل']
  },
  OTHER: {
    id: 'OTHER',
    code: 7,
    name: 'Other Plastics',
    name_ar: 'بلاستيك آخر',
    commonName: 'Mixed',
    structure: '',
    formula: 'Various',
    polymerization: 'Various',
    properties: ['Varies by type'],
    safety: 'Check specific material. May contain BPA.',
    safety_ar: 'تحقق من المادة المحددة. قد يحتوي على BPA.',
    sustainability: 'Usually non-recyclable - Code #7',
    description_ar: 'مواد بلاستيكية متنوعة.',
    recyclabilityScore: 10,
    degradationYears: 700,
    polymerCategory: 'thermoplastic',
    chemicalBonds: 'Various',
    commonUses: ['Polycarbonate', 'Nylon', 'Acrylic', 'Mixed materials'],
    commonUses_ar: ['بولي كربونات', 'نايلون', 'أكريليك', 'مواد مختلطة']
  }
};

export const ELEMENTS: ElementData[] = [
  // Period 1
  { number: 1, symbol: 'H', name: 'Hydrogen', name_ar: 'هيدروجين', mass: 1.008, category: 'nonmetal', config: '1s^1', summary: 'Most abundant element.', summary_ar: 'العنصر الأكثر وفرة.', row: 1, col: 1 },
  { number: 2, symbol: 'He', name: 'Helium', name_ar: 'هيليوم', mass: 4.0026, category: 'noble', config: '1s^2', summary: 'Second lightest element.', summary_ar: 'ثاني أخف عنصر.', row: 1, col: 18 },
  // Period 2
  { number: 3, symbol: 'Li', name: 'Lithium', name_ar: 'ليثيوم', mass: 6.94, category: 'alkali', config: '[He] 2s^1', summary: 'Used in batteries.', summary_ar: 'يستخدم في البطاريات.', row: 2, col: 1 },
  { number: 4, symbol: 'Be', name: 'Beryllium', name_ar: 'بيريليوم', mass: 9.0122, category: 'alkaline', config: '[He] 2s^2', summary: 'Rare element.', summary_ar: 'عنصر نادر.', row: 2, col: 2 },
  { number: 5, symbol: 'B', name: 'Boron', name_ar: 'بورون', mass: 10.81, category: 'metalloid', config: '[He] 2s^2 2p^1', summary: 'Used in fiberglass.', summary_ar: 'يستخدم في الألياف.', row: 2, col: 13 },
  { number: 6, symbol: 'C', name: 'Carbon', name_ar: 'كربون', mass: 12.011, category: 'nonmetal', config: '[He] 2s^2 2p^2', summary: 'Foundation of life.', summary_ar: 'أساس الحياة.', row: 2, col: 14 },
  { number: 7, symbol: 'N', name: 'Nitrogen', name_ar: 'نيتروجين', mass: 14.007, category: 'nonmetal', config: '[He] 2s^2 2p^3', summary: '78% of atmosphere.', summary_ar: '78٪ من الجو.', row: 2, col: 15 },
  { number: 8, symbol: 'O', name: 'Oxygen', name_ar: 'أكسجين', mass: 15.999, category: 'nonmetal', config: '[He] 2s^2 2p^4', summary: 'Essential for life.', summary_ar: 'ضروري للحياة.', row: 2, col: 16 },
  { number: 9, symbol: 'F', name: 'Fluorine', name_ar: 'فلور', mass: 18.998, category: 'halogen', config: '[He] 2s^2 2p^5', summary: 'Highly reactive.', summary_ar: 'شديد التفاعل.', row: 2, col: 17 },
  { number: 10, symbol: 'Ne', name: 'Neon', name_ar: 'نيون', mass: 20.180, category: 'noble', config: '[He] 2s^2 2p^6', summary: 'Used in signs.', summary_ar: 'يستخدم في الإضاءة.', row: 2, col: 18 },
  // Period 3
  { number: 11, symbol: 'Na', name: 'Sodium', name_ar: 'صوديوم', mass: 22.990, category: 'alkali', config: '[Ne] 3s^1', summary: 'Reactive soft metal.', summary_ar: 'معدن طري نشط.', row: 3, col: 1 },
  { number: 12, symbol: 'Mg', name: 'Magnesium', name_ar: 'مغنيسيوم', mass: 24.305, category: 'alkaline', config: '[Ne] 3s^2', summary: 'Essential nutrient.', summary_ar: 'مغذٍ أساسي.', row: 3, col: 2 },
  { number: 13, symbol: 'Al', name: 'Aluminium', name_ar: 'ألمنيوم', mass: 26.982, category: 'post-transition', config: '[Ne] 3s^2 3p^1', summary: 'Abundant metal.', summary_ar: 'معدن متوفر.', row: 3, col: 13 },
  { number: 14, symbol: 'Si', name: 'Silicon', name_ar: 'سيليكون', mass: 28.085, category: 'metalloid', config: '[Ne] 3s^2 3p^2', summary: 'Computer chips.', summary_ar: 'رقائق الحاسوب.', row: 3, col: 14 },
  { number: 15, symbol: 'P', name: 'Phosphorus', name_ar: 'فوسفور', mass: 30.974, category: 'nonmetal', config: '[Ne] 3s^2 3p^3', summary: 'Used in matches.', summary_ar: 'يستخدم في الثقاب.', row: 3, col: 15 },
  { number: 16, symbol: 'S', name: 'Sulfur', name_ar: 'كبريت', mass: 32.06, category: 'nonmetal', config: '[Ne] 3s^2 3p^4', summary: 'Yellow solid.', summary_ar: 'صلب أصفر.', row: 3, col: 16 },
  { number: 17, symbol: 'Cl', name: 'Chlorine', name_ar: 'كلور', mass: 35.45, category: 'halogen', config: '[Ne] 3s^2 3p^5', summary: 'Disinfectant.', summary_ar: 'مطهر.', row: 3, col: 17 },
  { number: 18, symbol: 'Ar', name: 'Argon', name_ar: 'أرجون', mass: 39.948, category: 'noble', config: '[Ne] 3s^2 3p^6', summary: 'Inert gas.', summary_ar: 'غاز خامل.', row: 3, col: 18 },
  // Period 4
  { number: 19, symbol: 'K', name: 'Potassium', name_ar: 'بوتاسيوم', mass: 39.098, category: 'alkali', config: '[Ar] 4s^1', summary: 'Plant nutrient.', summary_ar: 'مغذٍ للنبات.', row: 4, col: 1 },
  { number: 20, symbol: 'Ca', name: 'Calcium', name_ar: 'كالسيوم', mass: 40.078, category: 'alkaline', config: '[Ar] 4s^2', summary: 'Bone health.', summary_ar: 'صحة العظام.', row: 4, col: 2 },
  { number: 21, symbol: 'Sc', name: 'Scandium', name_ar: 'سكانديوم', mass: 44.956, category: 'transition', config: '[Ar] 3d^1 4s^2', summary: 'Aerospace.', summary_ar: 'الفضاء.', row: 4, col: 3 },
  { number: 22, symbol: 'Ti', name: 'Titanium', name_ar: 'تيتانيوم', mass: 47.867, category: 'transition', config: '[Ar] 3d^2 4s^2', summary: 'Strong, lightweight.', summary_ar: 'قوي وخفيف.', row: 4, col: 4 },
  { number: 23, symbol: 'V', name: 'Vanadium', name_ar: 'فاناديوم', mass: 50.942, category: 'transition', config: '[Ar] 3d^3 4s^2', summary: 'Steel alloy.', summary_ar: 'سبائك الصلب.', row: 4, col: 5 },
  { number: 24, symbol: 'Cr', name: 'Chromium', name_ar: 'كروم', mass: 51.996, category: 'transition', config: '[Ar] 3d^5 4s^1', summary: 'Stainless steel.', summary_ar: 'الصلب المقاوم للصدأ.', row: 4, col: 6 },
  { number: 25, symbol: 'Mn', name: 'Manganese', name_ar: 'منغنيز', mass: 54.938, category: 'transition', config: '[Ar] 3d^5 4s^2', summary: 'Railroads.', summary_ar: 'السكك الحديدية.', row: 4, col: 7 },
  { number: 26, symbol: 'Fe', name: 'Iron', name_ar: 'حديد', mass: 55.845, category: 'transition', config: '[Ar] 3d^6 4s^2', summary: 'Most used metal.', summary_ar: 'أكثر المعادن استخداماً.', row: 4, col: 8 },
  { number: 27, symbol: 'Co', name: 'Cobalt', name_ar: 'كوبالت', mass: 58.933, category: 'transition', config: '[Ar] 3d^7 4s^2', summary: 'Batteries.', summary_ar: 'البطاريات.', row: 4, col: 9 },
  { number: 28, symbol: 'Ni', name: 'Nickel', name_ar: 'نيكل', mass: 58.693, category: 'transition', config: '[Ar] 3d^8 4s^2', summary: 'Corrosion resistant.', summary_ar: 'مقاوم للتآكل.', row: 4, col: 10 },
  { number: 29, symbol: 'Cu', name: 'Copper', name_ar: 'نحاس', mass: 63.546, category: 'transition', config: '[Ar] 3d^10 4s^1', summary: 'Electrical wires.', summary_ar: 'أسلاك الكهرباء.', row: 4, col: 11 },
  { number: 30, symbol: 'Zn', name: 'Zinc', name_ar: 'زنك', mass: 65.38, category: 'transition', config: '[Ar] 3d^10 4s^2', summary: 'Galvanization.', summary_ar: 'الجلفنة.', row: 4, col: 12 },
  { number: 31, symbol: 'Ga', name: 'Gallium', name_ar: 'غاليوم', mass: 69.723, category: 'post-transition', config: '[Ar] 3d^10 4s^2 4p^1', summary: 'Low melting point.', summary_ar: 'درجة انصهار منخفضة.', row: 4, col: 13 },
  { number: 32, symbol: 'Ge', name: 'Germanium', name_ar: 'جرمانيوم', mass: 72.63, category: 'metalloid', config: '[Ar] 3d^10 4s^2 4p^2', summary: 'Semiconductors.', summary_ar: 'أشباه موصلات.', row: 4, col: 14 },
  { number: 33, symbol: 'As', name: 'Arsenic', name_ar: 'زرنيخ', mass: 74.922, category: 'metalloid', config: '[Ar] 3d^10 4s^2 4p^3', summary: 'Toxic metalloid.', summary_ar: 'شبه معدن سام.', row: 4, col: 15 },
  { number: 34, symbol: 'Se', name: 'Selenium', name_ar: 'سيلينيوم', mass: 78.971, category: 'nonmetal', config: '[Ar] 3d^10 4s^2 4p^4', summary: 'Photocells.', summary_ar: 'خلايا ضوئية.', row: 4, col: 16 },
  { number: 35, symbol: 'Br', name: 'Bromine', name_ar: 'بروم', mass: 79.904, category: 'halogen', config: '[Ar] 3d^10 4s^2 4p^5', summary: 'Liquid halogen.', summary_ar: 'هالوجين سائل.', row: 4, col: 17 },
  { number: 36, symbol: 'Kr', name: 'Krypton', name_ar: 'كريبتون', mass: 83.798, category: 'noble', config: '[Ar] 3d^10 4s^2 4p^6', summary: 'Lighting.', summary_ar: 'إضاءة.', row: 4, col: 18 },
  // Selected Heavy Elements
  { number: 47, symbol: 'Ag', name: 'Silver', name_ar: 'فضة', mass: 107.87, category: 'transition', config: '[Kr] 4d^10 5s^1', summary: 'Conductive metal.', summary_ar: 'معدن موصل.', row: 5, col: 11 },
  { number: 50, symbol: 'Sn', name: 'Tin', name_ar: 'قصدير', mass: 118.71, category: 'post-transition', config: '[Kr] 4d^10 5s^2 5p^2', summary: 'Used in solder.', summary_ar: 'يستخدم في اللحام.', row: 5, col: 14 },
  { number: 53, symbol: 'I', name: 'Iodine', name_ar: 'يود', mass: 126.90, category: 'halogen', config: '[Kr] 4d^10 5s^2 5p^5', summary: 'Antiseptic.', summary_ar: 'مطهر.', row: 5, col: 17 },
  { number: 79, symbol: 'Au', name: 'Gold', name_ar: 'ذهب', mass: 196.97, category: 'transition', config: '[Xe] 4f^14 5d^10 6s^1', summary: 'Precious metal.', summary_ar: 'معدن ثمين.', row: 6, col: 11 },
  { number: 80, symbol: 'Hg', name: 'Mercury', name_ar: 'زئبق', mass: 200.59, category: 'transition', config: '[Xe] 4f^14 5d^10 6s^2', summary: 'Liquid metal.', summary_ar: 'معدن سائل.', row: 6, col: 12 },
  { number: 82, symbol: 'Pb', name: 'Lead', name_ar: 'رصاص', mass: 207.2, category: 'post-transition', config: '[Xe] 4f^14 5d^10 6s^2 6p^2', summary: 'Dense metal.', summary_ar: 'معدن كثيف.', row: 6, col: 14 },
  { number: 92, symbol: 'U', name: 'Uranium', name_ar: 'يورانيوم', mass: 238.03, category: 'actinide', config: '[Rn] 5f^3 6d^1 7s^2', summary: 'Nuclear fuel.', summary_ar: 'وقود نووي.', row: 9, col: 6 }
];